version: '3.8'

services:
  web:
    build:
      context: .
    container_name: my_web_app
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_DATABASE=my_database
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: my_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:

  
